src/DrDiet/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrDiet.Data;
using DrDiet.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DrDiet.Controllers
{
    public class RecipesController : Controller
    {
        private readonly DrdietContext _ctx;

        public RecipesController(DrdietContext ctx)
        {
            this._ctx = ctx;
        }

        public IActionResult Index()
        {
            var model = _ctx.Recipes
                .Include(r => r.Ingredients)
                .ThenInclude(i => i.Product);
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var model = _ctx.Recipes
                .Where(r => r.Id == id)
                .Include(r => r.Ingredients)
                .ThenInclude(i => i.Product)
                .FirstOrDefault();

            ViewBag.products = _ctx.Products.OrderBy(p => p.Name);

            return View(model);
        }

        public IActionResult DeleteIngredient(int modelId, int ingedientId)
        {
            var model = _ctx.Recipes
                .Where(r => r.Id == modelId)
                .Include(r => r.Ingredients)
                .ThenInclude(i => i.Product)
                .FirstOrDefault();

            var ingredientToRemove = model.Ingredients.FirstOrDefault(i => i.Id == ingedientId);
            model.Ingredients.Remove(ingredientToRemove);
            _ctx.Remove(ingredientToRemove);

            _ctx.Recipes.Update(model);
            _ctx.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = modelId });
        }

        public IActionResult AddIngredient(int modelId, int productId, int weightInGrams)
        {
            var model = _ctx.Recipes
                .Where(r => r.Id == modelId)
                .Include(r => r.Ingredients)
                .ThenInclude(i => i.Product)
                .FirstOrDefault();

            var product = _ctx.Products.Find(productId);
            var ammountInKilos = (double)weightInGrams / 1000.0;
            var newIngredient = new Ingredient() { Ammount = ammountInKilos, Product = product };
            model.Ingredients.Add(newIngredient);

            _ctx.Recipes.Update(model);
            _ctx.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = modelId });
        }

        public IActionResult Rename(int id, string newName)
        {
            var model = _ctx.Recipes.Find(id);
            model.Name = newName;

            _ctx.Update(model);
            _ctx.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = id });
        }

        public IActionResult EditInstructions(int id, string newInstructions)
        {
            var model = _ctx.Recipes.Find(id);
            model.Instructions = newInstructions;

            _ctx.Update(model);
            _ctx.SaveChanges();

            return RedirectToAction(nameof(Edit), new { id = id });
        }

        public IActionResult Add([FromForm] Recipe recipe)
        {
            // TODO: add ViewModel insted adapting ammount
            if (recipe.Ingredients is { })
            {

                var usedProductIds = recipe.Ingredients.Select(i => i.Product).Select(p => p.Id);
                var productsInDb = _ctx.Products.Where(p => usedProductIds.Contains(p.Id)).ToDictionary(p => p.Id, p => p);
                foreach(var ingredient in recipe.Ingredients)
                {
                    ingredient.Product = productsInDb[ingredient.Product.Id];
                    ingredient.Ammount /= 1000;
                }
                _ctx.Recipes.Add(recipe);
                _ctx.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.products = _ctx.Products.OrderBy(p => p.Name);

            return View();
        }

        public IActionResult Delete(int id)
        {
            var recipeToDelete = _ctx.Recipes
                .Where(r => r.Id == id)
                .Include(r => r.Ingredients)
                .FirstOrDefault();
            recipeToDelete.Ingredients.ToList().ForEach(i => _ctx.Remove(i));
            _ctx.Recipes.Remove(recipeToDelete);
            _ctx.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


    }
}

src/DrDiet/Views/Recipes/add.cshtml
<h1>Add Recipe</h1>

<div class="container">
    <div class="row justify-content-end">
        <div id="kcal_info" class="btn btn-outline-secondary col-2">0 kcal</div>
        <div class="col-1">&nbsp;</div>
    </div>
</div>
@using (Html.BeginForm("Add", "Recipes", FormMethod.Post))
{
    <div>
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <input name="id" type="hidden" value="" class="form-control" />
                    <input name="name" type="text" value="" class="form-control" />
                </div>
            </div>
        </div>
    </div>
    <table id="ingredients_table" class="table">
        <thead>
            <tr>
                <th scope="col">Nazwa</th>
                <th scope="col">Ilość</th>
                <th scope="col">Kalorie</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody id="ingredients_table_body" >
            @*<tr id="empty_row">
                        <td id="name_cell">&nbsp;</td>
                        <td id="amount_cell">&nbsp;</td>
                        <td id="energy_cell">&nbsp;</td>
                        <td><button class="btn btn-danger small_button">Delete</button></td>
                    </tr>
                </tbody>*@
            <tr id="newProductRow">
                <td>
                    <select class="available_products form-control" name="ingredients[0].Product.Id" onchange="update_kcals(this.name)">
                        @foreach (var option in ViewBag.products)
                        {
                            <option value="@option.Id" data="@option.Energy">@option.Name</option>
                        }
                    </select>
                </td>
                <td>
                    <input class="weight_in_grams form-control" name="ingredients[0].Ammount" type="number" value="" oninput="update_kcals(this.name)" />
                </td>
                <td>
                    <input class="kcals form-control" name="kcals" type="number" value="" disabled />
                </td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <div class="float-right">
        <button id="add_ingredient_button" class="btn btn-primary small_button" type="button" onclick="addIngredientRow()">Add Ingredient</button>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-9">
                <textarea name="instructions" class="form-control"></textarea>
            </div>
        </div>
    </div>
    <div>&nbsp;</div>
    <div>
        <input type="submit" value="Submit" class="btn btn-outline-primary small_button float-right" />
    </div>
    <div>&nbsp;</div>
}
<script src="~/js/recipes_add.js"></script>

src/DrDiet/Views/Recipes/edit.cshtml
@model Recipe
<h1>Change recipe:</h1>

<div class="container">
    <div class="row justify-content-end">
        <div id="kcal_info" class="btn btn-outline-secondary col-2">@Math.Round(Model.Ingredients.Sum(i => i.Ammount * (double)i.Product.Energy), 0) kcal</div>
        <div class="col-1">&nbsp;</div>
    </div>
</div>
<div>
    <div id="recipe_name" class="float-left">@Model.Name</div>
    <button id="rename_recipe" class="btn btn-primary small_button" onclick="enableRename()">Rename</button>
    <div id="rename_form" style="display: none" class="container">
        @using (Html.BeginForm("Rename", "Recipes", FormMethod.Post))
        {
        <div class="row">
            <input name="id" type="hidden" value="@Model.Id" />
            <div class="col-9">
                <input name="newName" type="text" value="@Model.Name" class="form-control" />
            </div>
            <div class="col">
                <a id="cancel_rename" class="btn btn-warning small_button" onclick="disableRename()">Cancel</a>
                <input type="submit" value="Submit" class="btn btn-outline-primary small_button" />
            </div>
        </div>
        }
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Nazwa</th>
            <th scope="col">Ilość</th>
            <th scope="col">Kalorie</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    @foreach (var i in Model.Ingredients)
    {
        <tr>
            <td>@i.Product.Name</td>
            <td>@(i.Ammount*1000) g</td>
            <td>@(Math.Round((double)i.Product.Energy * i.Ammount, 0)) kcal</td>
            <td>
                <a asp-controller="Recipes"
                   asp-action="DeleteIngredient"
                   asp-route-modelId="@Model.Id"
                   asp-route-ingedientId="@i.Id"
                   class="btn btn-danger small_button">
                    Delete
                </a>
            </td>
        </tr>
    }
    <tr>
        @using (Html.BeginForm("AddIngredient", "Recipes", FormMethod.Post))
        {
        <td>
            <select id="available_products" name="productId" class="form-control" onchange="update_kcals()">
                @foreach (var option in ViewBag.products)
                {
                    <option value="@option.Id" data="@option.Energy">@option.Name</option>
                    }
            </select>
        </td>
        <td>
            <input name="modelId" type="hidden" value="@Model.Id"/>
            <input id="weight_in_grams" name="weightInGrams" type="number" value="" oninput="update_kcals()" class="form-control"/>
        </td>
        <td>
            <input id="kcals" name="kcals" type="number" value="" disabled class="form-control"/>
        </td>
        <td>
            <button type="submit" id="submit_button" class="btn btn-primary small_button">Add</button>
        </td>
        }
    </tr>
</table>
<div class="container">
    <div id="instructions" class="float-left">@Model.Instructions</div>
    <button id="enable_instructions_edit_button" class="btn btn-primary small_button" onclick="enableInstructionsEdit()">Edit</button>
    <div id="edit_instructions_form" style="display: none">
        @using (Html.BeginForm("EditInstructions", "Recipes", FormMethod.Post))
        {
        <div class="row">
            <input name="id" type="hidden" value="@Model.Id" />
            <div class="col-9">
                <textarea name="newInstructions" class="form-control">@Model.Instructions</textarea>
            </div>
            <div class="col">
                <a id="cancel_edit_instructions" class="btn btn-warning small_button" onclick="disableInstructionsEdit()">Cancel</a>
                <input type="submit" value="Submit" class="btn btn-outline-primary small_button" />
            </div>
        </div>
        }
    </div>
</div>
<div>&nbsp;</div>
<script src="~/js/recipes_edit.js"></script>

src/DrDiet/Views/Recipes/index.cshtml
@model IEnumerable<Recipe>
<h1>Recipes:</h1>
<p>Count: @Model.Count()</p>

<a asp-action="Add" asp-controller="Recipes" class="btn btn-primary small_button">Add Recipe</a>
@foreach (var r in Model)
{
    <div class="float-right">
        <a asp-action="Edit" asp-controller="Recipes" asp-route-id="@r.Id" class="btn btn-primary small_button">Edit</a>
        <a asp-action="Delete" asp-controller="Recipes" asp-route-id="@r.Id" class="btn btn-danger small_button">Delete</a>
    </div>
    <div>
        <div>@r.Name</div>
        <div>@(Math.Round(r.Ingredients.Sum(i => i.Ammount * (double)i.Product.Energy), 0)) kcal</div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nazwa</th>
                <th scope="col">Ilość</th>
                <th scope="col">Kalorie</th>
            </tr>
        </thead>
        @foreach (var i in r.Ingredients)
        {
            <tr>
                <td>@i.Product.Name</td>
                <td>@(i.Ammount*1000) g</td>
                <td>@(Math.Round((double)i.Product.Energy * i.Ammount, 0)) kcal</td>
            </tr>
        }
    </table>
    <div>@r.Instructions</div>
}