src/DrDiet/Controllers/MenuController.cs
using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrDiet.Data;
using DrDiet.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace DrDiet.Controllers
{
    public class MenuController : Controller
    {
        private readonly DrdietContext _ctx;

        public MenuController(DrdietContext _ctx)
        {
            this._ctx = _ctx;
        }
        public IActionResult Index()
        {
            var model = _ctx.MenuPositions
                .Include(m => m.Courses)
                    .ThenInclude(c => c.Recipe)
                    .ThenInclude(r => r.Ingredients)
                    .ThenInclude(i => i.Product)
                .Include(m => m.OtherProducts)
                    .ThenInclude(p => p.Product);
            //return RedirectToAction(nameof(Add));
            return View(model);

        }
        public IActionResult Add([FromForm] MenuPosition newPosition)
        {
            if (newPosition.Courses is { } || newPosition.OtherProducts is { })
            {
                var usedRecipesIds = newPosition.Courses?.Select(c => c.Recipe.Id) ?? Enumerable.Empty<int>();
                var recipesInDb = _ctx.Recipes.Where(r => usedRecipesIds.Contains(r.Id))
                    .ToDictionary(r => r.Id, r => r);
                foreach (var course in newPosition.Courses ?? Enumerable.Empty<Course>())
                {
                    course.Ammount /= 1000;
                    course.Recipe = recipesInDb[course.Recipe.Id];
                }

                var usedProductIds = newPosition.OtherProducts?.Select(i => i.Product).Select(p => p.Id) ?? Enumerable.Empty<int>();
                var productsInDb = _ctx.Products.Where(p => usedProductIds.Contains(p.Id)).ToDictionary(p => p.Id, p => p);
                foreach (var otherProduct in newPosition.OtherProducts ?? Enumerable.Empty<Ingredient>())
                {
                    otherProduct.Product = productsInDb[otherProduct.Product.Id];
                    otherProduct.Ammount /= 1000;
                }

                _ctx.MenuPositions.Add(newPosition);
                _ctx.SaveChanges();
            }

            ViewBag.recipes = _ctx.Recipes.Include(r=>r.Ingredients).ThenInclude(i => i.Product).OrderBy(p => p.Name);
            ViewBag.products = _ctx.Products.OrderBy(p => p.Name);

            return View();
        }

        public IActionResult Edit()
        {
            throw new NotImplementedException();
        }

        public IActionResult Delete()
        {
            throw new NotImplementedException();
        }
    }
}

src/DrDiet/Views/Menu/add.cshtml
@section scripts {
    <script src="~/node_modules/popper.js/dist/popper.js/popper.min.js"></script>
    <script src="~/node_modules/moment/min/moment.min.js"></script>
    <script src="~/node_modules/pc-bootstrap4-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/menu_position_add.js"></script>
}
<h1>Add Menu Position</h1>
<link href="~/node_modules/pc-bootstrap4-datetimepicker/build/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />

<div class="container">
    <div class="row justify-content-end">
        <div id="kcal_info" class="btn btn-outline-secondary col-2">0 kcal</div>
        <div class="col-1">&nbsp;</div>
    </div>
</div>
@using (Html.BeginForm("Add", "Menu", FormMethod.Post))
{
    <div>
        <div class="container">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <div class='input-group date'>
                            <p>Date and time:</p>
                            <input name="DateTime" type='text' class="form-control" id="my-datetimepicker" value="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table id="courses-table" class="table">
        <thead>
            <tr>
                <th scope="col">Nazwa</th>
                <th scope="col">Ilość</th>
                <th scope="col">Kalorie</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody id="menu-components-table-body" >
            <tr id="new-course-row" style="display: none">
                <td>
                    <select class="available_recipes form-control" onchange="update_kcals_courses(this.name)">
                        @foreach (var recipe in ViewBag.recipes)
                        {
                            <option value="@recipe.Id" data="@recipe.GetTotalEnergyPerKilo()">@recipe.Name</option>
                        }
                    </select>
                </td>
                <td>
                    <input class="weight_in_grams_courses form-control" type="number" value="" oninput="update_kcals_courses(this.name)" />
                </td>
                <td>
                    <input class="kcals kcals_courses form-control" name="kcals" type="number" value="" disabled />
                </td>
                <td><button type="button" class="btn btn-danger delete_button">Delete</button></td>
            </tr>
            <tr id="new-ingredient-row" style="display: none">
                <td>
                    <select class="available_products form-control" onchange="update_kcals_ingredients(this.name)">
                        @foreach (var option in ViewBag.products)
                        {
                            <option value="@option.Id" data="@option.Energy">@option.Name</option>
                        }
                    </select>
                </td>
                <td>
                    <input class="weight_in_grams_ingredients form-control" type="number" value="" oninput="update_kcals_ingredients(this.name)" />
                </td>
                <td>
                    <input class="kcals kcals_ingredients form-control" name="kcals" type="number" value="" disabled />
                </td>
                <td><button type="button" class="btn btn-danger delete_button">Delete</button></td>
            </tr>
        </tbody>
    </table>
    <div class="float-right">
        <button id="add-course-button" class="btn btn-primary small_button" type="button" onclick="addCourseRow()">Add Course</button>
        <button id="add-ingredient-button" class="btn btn-primary small_button" type="button" onclick="addIngredientRow()">Add Ingredient</button>
    </div>
    <div>&nbsp;</div>
    <div>
        <input type="submit" value="Submit" class="btn btn-outline-primary small_button float-right" />
    </div>
    <div>&nbsp;</div>
}

src/DrDiet/Views/Menu/index.cshtml
@model IEnumerable<MenuPosition>
<h1>Menu Positions:</h1>
<p>Count: @Model.Count()</p>

<a asp-action="Add" asp-controller="Menu" class="btn btn-primary small_button">Add Menu Position</a>
@foreach (var menuPosition in Model)
{
    <div class="float-right">
        <a asp-action="Edit" asp-controller="Menu" asp-route-id="@menuPosition.Id" class="btn btn-primary small_button">Edit</a>
        <a asp-action="Delete" asp-controller="Menu" asp-route-id="@menuPosition.Id" class="btn btn-danger small_button">Delete</a>
    </div>
    <div>
        <div>@menuPosition.DateTime</div>
        <div>@(Math.Round(0
                          + (menuPosition.Courses?.Sum(c => c.Ammount * (double)c.Recipe.GetTotalEnergy() * c.Recipe.GetMultiplierToKilo()) ?? 0)
                          + (menuPosition.OtherProducts?.Sum(o => o.Ammount * (double)o.Product.Energy) ?? 0)
                         ,0)) kcal</div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nazwa</th>
                <th scope="col">Ilość</th>
                <th scope="col">Kalorie</th>
            </tr>
        </thead>
        @foreach (var course in menuPosition.Courses ?? Enumerable.Empty<Course>())
        {
            <tr>
                <td>@course.Recipe.Name</td>
                <td>@(course.Ammount*1000) g</td>
                <td>@(Math.Round((double)course.Recipe.GetTotalEnergy() * course.Recipe.GetMultiplierToKilo() * course.Ammount, 0)) kcal</td>
            </tr>
            @foreach (var ingredient in course.Recipe.Ingredients)
            {
                <tr>
                    <td class="nested_row gray_td">&#8226; @ingredient.Product.Name</td>
                    <td class="gray_td">@Math.Round(ingredient.Ammount * course.Recipe.GetMultiplierToKilo() * course.Ammount * 1000, 0) g</td>
                    <td class="gray_td">@Math.Round((double) ingredient.Product.Energy * ingredient.Ammount * course.Recipe.GetMultiplierToKilo() * course.Ammount, 0)</td>
                </tr>
            }
        }
        @foreach (var ingredient in menuPosition.OtherProducts ?? Enumerable.Empty<Ingredient>())
        {
            <tr>
                <td>@ingredient.Product.Name</td>
                <td>@(ingredient.Ammount*1000) g</td>
                <td>@(Math.Round((double)ingredient.Product.Energy * ingredient.Ammount, 0)) kcal</td>
            </tr>
        }
    </table>
}